NVIDIA: SAUCE: Revert "eth: bnxt: remove most dependencies on RTNL"
BugLink: https://bugs.launchpad.net/bugs/2124107

This reverts commit 1bcb53c504dd17946a059c5c746266f455ee8383.

In order to avoid a build failure of DOCA's mlnx-ofed-kernel, remove the
definition of netdev_trylock() from include/linux/netdevice.h.

This effectively reverts the previous partial backport of commit
004b5008016a ("eth: bnxt: remove most dependencies on RTNL").

Upstream, netdev_trylock() has the following history:

commit 004b5008016a ("eth: bnxt: remove most dependencies on RTNL")
	Introduces netdev_trylock() in include/linux/netdevice.h

commit 8ef890df4031 ("net: move misc netdev_lock flavors to a separate
header")
	Moves netdev_trylock() and other functions to the new
	include/net/netdev_lock.h

https://github.com/NVIDIA/NV-Kernels/pull/216 added a partial backport of
004b5008016a but not 8ef890df4031. As a result, netdev_trylock() is
currently defined in include/linux/netdevice.h. 004b5008016a was included
as a dependency of commit e80d65561571 ("net/mlx5e: Fix potential deadlock
by deferring RX timeout recovery").

Meanwhile, mlnx-ofed-kernel 25.10.OFED.25.10.1.2.2.1 fails to build on the
current branch:

In file included from drivers/net/ethernet/mellanox/mlx5/core/en_main.c:36:
/var/lib/dkms/mlnx-ofed-kernel/25.10.OFED.25.10.1.2.2.1/build/include/net/netdev_lock.h:13:20: error: redefinition of ‘netdev_trylock’
   13 | static inline bool netdev_trylock(struct net_device *dev)
      |                    ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/mlnx-ofed-kernel/25.10.OFED.25.10.1.2.2.1/build/include/linux/netdevice.h:7,
                 from /var/lib/dkms/mlnx-ofed-kernel/25.10.OFED.25.10.1.2.2.1/build/include/net/netdev_lock.h:11:
/usr/src/linux-headers-6.14.0-2013-nvidia-64k/include/linux/netdevice.h:2713:20: note: previous definition of ‘netdev_trylock’ with type ‘bool(struct net_device *)’ {aka ‘_Bool(struct net_device *)’}
 2713 | static inline bool netdev_trylock(struct net_device *dev)
      |                    ^~~~~~~~~~~~~~

This version of ofed expects either netdev_trylock() to be absent or to be
defined in include/net/netdev_lock.h; not in include/linux/netdevice.h.

Other approaches that were considered:
* add a partial backport of 8ef890df4031 which creates
  include/net/netdev_lock.h and moves netdev_trylock() to it.
	Commit 8ef890df4031 does not apply cleanly on the current branch.
	Having a version of include/net/netdev_lock.h that differs from
	upstream might lead to similar problems with ofed in the future.
* change the config tests in ofed to support kernels that have
  netdev_trylock() defined in include/linux/netdevice.h
	The ofed team considered this option but preferred the current
	revert approach. In general, ofed does not support kernels with a
	mix of backports.

Signed-off-by: Benjamin Poirier <bpoirier@nvidia.com>
Acked-by: Carol L Soto <csoto@nvidia.com>
Acked-by: Jamie Nguyen <jamien@nvidia.com>
Acked-by: Nirmoy Das <nirmoyd@nvidia.com>
Acked-by: Acked-by: jamieNguyenNVIDIA
Acked-by: Acked-by: jamieNguyenNVIDIA
Acked-by: Acked-by: jamieNguyenNVIDIA